version: "3.5"
services:
    jellyfin:
      image: jellyfin/jellyfin
      container_name: jellyfin
      user: 1000:1000
      network_mode: "host"
      volumes:
         - ~/jellyfin/config:/config
         - ~/jellyfin/cache:/cache
         - ~:/media
      restart: "unless-stopped"
                                                                              #
    jackett:
      image: lscr.io/linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Sao_Paulo
        - AUTO_UPDATE=true #optional
          #- RUN_OPTS=<run options here> #optional
      volumes:
        - ~/.jackett/data:/config
        - ~/.jackett/blackhole:/downloads
      ports:
        - 9117:9117
      restart: unless-stopped

