#!/usr/bin/zsh

subliminal --addic7ed gavieira $(pass addic7ed) --legendastv gavieira $(pass legendastv) --opensubtitles Deusdeth $(pass opensubtitles) download -p opensubtitles -l en -l pt -l pt-BR . && 
subliminal --addic7ed gavieira $(pass addic7ed) --legendastv gavieira $(pass legendastv) --opensubtitles Deusdeth $(pass opensubtitles) download -l en -l pt -l pt-BR .
